const symposiumText = `APOLLODORUS: I believe I am quite well prepared to relate the events you are asking me about, for just the other day I happened to be going into Athens from my home in Phalerum when an acquaintance of mine caught sight of me from behind and called after me, jokily, \n
    'Phalerian! You there, Apollodorus! Wait for me, will you?' \n
    So I stopped and waited. \n
    'I have just been looking for you, Apollodorus. I wanted to get from you the story about that party of Agathon's with Socrates, Alcibiades and the rest, the time when they were all together at dinner, and to hear what they said in their speeches on the subject of love. Someone else was telling me, who had heard about it from Phoenix, son of Philippus, and he said that you knew about it too. Actually he could not give any clear account of it, so you must tell me. You are in the best position to report the words of your friend. But tell me this first', he went on. \n
    'Were you at that party yourself or not?' \n
    'It certainly looks as if your informant was rather confused', I replied, 'if you think the party you are asking about occurred recently enough for me to be there'. \n
    'Yes, I did think so', he replied. (1) \n
    'But how could you think so, Glaucon?' I said. 'Don't you know that it is now many years since Agathon lived in Athens, and it is not yet three years since I began to associate with Socrates and to make it my daily business to know everything he says and does? Before that I used to think I was achieving something when I was in fact running round in circles aimlessly, in the most miserable state, just like you now, and I thought philosophy was the last thing I should be doing'. \n
    'Don't make fun of me', he said. 'Just tell me when that party took place'. \n
    'When you and I were still boys', I replied, 'in the year when Agathon won the prize with his first tragedy and on the day after he and the members of the cast held the sacrificial feast to celebrate the victory'. \n
    'Oh, then it really was a long time ago', he replied. 'But who told you about it? Was it Socrates himself?' \n
    'Certainly not', I said. 'It was actually the man who told Phoenix, someone called Aristodemus of Cydathenaeum, a small man, who never wore any shoes. He had been at the party, and I think there was no more devoted admirer of Socrates at that time. But of course I asked Socrates myself some questions afterwards about what I had heard from Aristodemus, and he confirmed what Aristodemus had said'. \n
    'Then', said Glaucon, 'do tell me. The city road is in any case convenient for conversation between fellow-travellers'. \n
    So it happened that as we went on our way we talked about the speeches, with the result that, as I said at the beginning, I am quite well prepared. If you really want me to recount them to all of you as well, then that is what I had better do. Anyway, whenever I talk myself on any philosophical subject or I listen to others talking, quite apart from thinking it is doing me good I enjoy it enormously. But when I listen to other kinds of discussion, especially from people like you, rich money-makers, I get (2) \
    bored on my own account and at the same time I feel sorry for you, my companions, because you think you are achieving something when you are achieving nothing. On the other hand you perhaps believe that I am the one who is unfortunate, and I suppose you are right. But in your case I don't merely suppose you are unfortunate, I know it. \n
    FRIEND: You are quite incorrigible, Apollodorus. You are always disparaging yourself and everyone else as well. I really do believe you think everyone except Socrates is miserable, starting with you. However you got that nickname, 'Softy', I cannot imagine. You are always like this when you speak, raging against yourself and everyone else except Socrates. \n
    APOLLODORUS: Obviously then, my dear friend, if I think as I do about myself and all of you I am completely mad! \n
    FRIEND: It is not worth quarrelling about these things now, Apollodorus. Please do what we asked you and tell us what they said in their speeches. \n
    APOLLODORUS: Well then, those speeches went something like this - no, I shall begin at the beginning and try to tell you the whole story as Aristodemus told me. \n
    Aristodemus said that he and Socrates chanced to meet when the latter was fresh from the baths and wearing his sandals, two rare events for him, so he asked him where he was going, having got himself up so beautifully. \n
    'To Agathon's for dinner', Socrates replied. 'I avoided the celebrations yesterday, being afraid of the crush, but I agreed I would come today. So that is why I have beautified myself like this, a beautiful guest for a beautiful host. But you, now: how do you feel about possibly coming to dinner when you have not been invited?' \n
    Aristodemus said that he replied, 'I shall do whatever you say'. \n
    'Well, come with me then', said Socrates, 'and we will spoil the old saying by altering the words. We will make it say that \"to good men's feasts good men go unbidden\". After all, Homer himself comes close not merely to spoiling it but to treating it with contempt. He represents Agamemnon as an exceptionally valiant warrior and Menelaus as \"a (3) \
    faint-hearted spearman\", and when Agamemnon after sacrificing is giving a banquet he has Menelaus coming to the feast unbidden, and so the worse man going to the feast of a better'. \n
    Aristodemus said that, after listening to this, he replied, 'I am rather afraid, Socrates, that in my case I shall come closer to Homer's version than to yours, being an inferior man going uninvited to the feast of a wise one. If you take me along you had better see what excuse you will give, because I shall not admit I came uninvited – I shall say I was invited by you'. \n
    '\"As we two go further on the way\"', was the reply, 'we shall decide on our story. Come on, now'. \n
    After a conversation like this Aristodemus said they walked on. As Socrates proceeded along the road he became absorbed in his own thoughts and started to fall behind; when Aristodemus waited Socrates told him to go on ahead. Arriving at Agathon's house Aristodemus found the door open and himself standing there, he said, in a ridiculous situation. One of the domestic servants immediately received him and led him to where all the other guests had taken their places, and he found them about to begin dinner. As soon as Agathon saw him he called out, 'Aristodemus, how lucky! You are just in time for dinner. If you have come for some other purpose, do postpone it. I was looking for you yesterday to invite you but I could not find you. But how is it you have not brought Socrates to join us?' \n
    I turned round to look behind me, Aristodemus said, but I could not see Socrates anywhere. So I replied that I had been invited there to dinner by Socrates and that it was I in fact who had come with him. \n
    'I am very glad you came', said Agathon, 'but where is the man?' 'He was coming into the house behind me just now. I wonder myself where he might be'. \n
    'Go and look for Socrates and bring him in', said Agathon to a servant. 'Now, Aristodemus, do take a place beside Eryximachus'. (4) \
    Aristodemus said that one servant brought him water to wash with before he took his place, while another appeared and said, 'Socrates is here but has withdrawn into your neighbours' doorway and is just standing there, and though I have been calling him he will not come inside'. \n
    'How odd', said Agathon. 'Call him again and keep on calling him'. \n
    'No', said Aristodemus, 'let him alone. This is one of his habits. \n
    Sometimes he turns aside and stands still wherever he happens to be. He will come in very soon, I think. Don't disturb him, leave him alone'. 'Well, if you think so then that is what we had better do', replied Agathon. 'Now, you servants, lay your feast before the rest of us. At any rate you put on the table whatever you like when no one is supervising you – and supervising is something I have never yet done. So on this occasion treat these other guests, as well as me, as if you had invited us all to dinner yourselves. Look after us well and you will earn our thanks'. After this they started dinner, Aristodemus said, but still Socrates did not come. Agathon kept trying to have him summoned but Aristodemus would not allow it. After delaying for a little while in that habitual way of his, Socrates eventually arrived, but by then they were about halfway through dinner. Agathon, who happened to be alone on the bottom couch, called out, 'Socrates, come over here beside me so that I may enjoy the benefit of being in contact with that piece of wisdom which came into your mind in that doorway. Obviously you are now in possession of the answer you were looking for, otherwise you would not have stopped looking'. \n
    Socrates sat down. 'It would be a happy state of affairs, Agathon, if wisdom were something that could flow between us through mere contact, from the one who is full to one who is empty, like water flowing along a strand of wool from a full cup to an empty one. If that is how it is with wisdom also, then I greatly value having the place next to you because I think that I shall get my fill from you of your abundant and beautiful wisdom. My own wisdom is certainly of an inferior sort, and, like a dream, of doubtful reality, whereas yours is already brilliant and full of promise – witness the fact that it was so conspicuous the day before yesterday and shone forth from you so splendidly, young as you are, in the presence of more than thirty thousand Greek spectators'. (5) \ `;

export default symposiumText;
